import type { UserRole } from '@/types';

export type RoutePermission = {
  path: string;
  label: string;
  icon?: string;
  roles: UserRole[];
  children?: RoutePermission[];
};

export const rolePermissions: Record<UserRole, string[]> = {
  EMPLOYEE: [
    '/dashboard',
    '/profile',
    '/my-team',
    '/attendance',
    '/leave',
    '/payroll',
    '/performance',
    '/documents',
    '/employees-directory',
    '/helpdesk',
    '/financeadmin/tickets',
    '/financeadmin/tickets',
    '/facilitiesadmin/tickets',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
    '/rmg/reports/employee-hours',
  ],
  MANAGER: [
    '/dashboard',
    '/manager/dashboard',
    '/manager/leave-approvals',
    '/profile',
    '/my-team',
    '/attendance',
    '/leave',
    '/payroll',
    '/performance',
    '/documents',
    '/helpdesk',
    '/helpdesk',
    '/employees-directory',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
    '/rmg/reports/employee-hours',
  ],
  IT_ADMIN: [
    '/dashboard',
    '/itadmin/dashboard',
    '/itadmin/tickets',
    '/itadmin/analytics',
    '/profile',
    '/my-team',
    '/attendance',
    '/leave',
    '/payroll',
    '/performance',
    '/documents',
    '/documents',
    '/employees-directory',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
  ],
  IT_EMPLOYEE: [
    '/dashboard',
    '/itadmin/tickets',
    '/itadmin/analytics',
    '/profile',
    '/my-team',
    '/attendance',
    '/leave',
    '/payroll',
    '/performance',
    '/documents',
    '/documents',
    '/employees-directory',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
  ],
  L1_APPROVER: [
    '/dashboard',
    '/approver',
    '/profile',
    '/profile',
    '/employees-directory',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
  ],
  L2_APPROVER: [
    '/dashboard',
    '/approver',
    '/profile',
    '/profile',
    '/employees-directory',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
  ],
  L3_APPROVER: [
    '/dashboard',
    '/approver',
    '/profile',
    '/profile',
    '/employees-directory',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
  ],
  SUPER_ADMIN: [
    '/dashboard',
    '/superadmin/dashboard',
    '/superadmin/categories',
    '/superadmin/approvers',
    '/superadmin/users',
    '/superadmin/configuration',
    '/profile',
    '/profile',
    '/employees-directory',

    // Full access to all routes
    '/my-team',
    '/attendance',
    '/leave',
    '/payroll',
    '/performance',
    '/documents',
    '/helpdesk',
    '/approver',
    '/itadmin/dashboard',
    '/itadmin/tickets',
    '/manager/dashboard',
    '/manager/leave-approvals',
    '/employees',
    '/attendance-management',
    '/leave-management',
    '/payroll-management',
    '/recruitment',
    '/performance-management',
    '/reports',
    '/resource-pool',
    '/allocations',
    '/utilization',
    '/forecasting',
    '/rmg/analytics',
    '/new-announcement',
    '/admin-announcements',
    '/rmg/customers',
    '/rmg/projects',
    '/rmg/customer-pos',
    '/rmg/financial-lines',
    '/rmg/reports/employee-hours',
    '/timesheet-management',
    '/timesheet-management/uda-configuration',
    '/timesheet-management/weekly-timesheet',
  ],
  HR: [
    '/dashboard',
    '/employees',
    '/attendance-management',
    '/leave-management',
    '/payroll-management',
    '/recruitment',
    '/performance-management',
    '/reports',
    '/employees-directory',
    '/new-announcement',
    '/new-announcement',
    '/admin-announcements',
    '/ctc-master',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
    '/rmg/reports/employee-hours',
  ],
  RMG: [
    '/dashboard',
    '/resource-pool',
    '/allocations',
    '/utilization',
    '/forecasting',
    '/rmg/analytics',
    '/rmg/customers',
    '/rmg/projects',
    '/rmg/customer-pos',
    '/rmg/financial-lines',
    '/reports',
    '/employees-directory',
    '/timesheet-management',
    '/timesheet-management',
    '/timesheet-management/uda-configuration',
    '/timesheet-management/weekly-timesheet',
    '/rmg/reports/employee-hours',
  ],
  FINANCE_ADMIN: [
    '/dashboard',
    '/financeadmin/dashboard',
    '/financeadmin/tickets',
    '/financeadmin/analytics',
    '/profile',
    '/profile',
    '/employees-directory',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
  ],
  FACILITIES_ADMIN: [
    '/dashboard',
    '/facilitiesadmin/dashboard',
    '/facilitiesadmin/tickets',
    '/facilitiesadmin/analytics',
    '/profile',
    '/profile',
    '/employees-directory',
    '/timesheet-management',
    '/timesheet-management/weekly-timesheet',
  ],
};

export const navigationConfig: RoutePermission[] = [
  // Common Dashboard
  {
    path: '/dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN', 'IT_EMPLOYEE', 'L1_APPROVER', 'L2_APPROVER', 'L3_APPROVER', 'HR', 'RMG', 'SUPER_ADMIN', 'FINANCE_ADMIN', 'FACILITIES_ADMIN'],
  },
  // Super Admin Routes
  {
    path: '/superadmin/dashboard',
    label: 'Super Admin',
    icon: 'ShieldCheck',
    roles: ['SUPER_ADMIN'],
  },
  {
    path: '/superadmin/categories',
    label: 'Category Management',
    icon: 'FolderCog',
    roles: ['SUPER_ADMIN'],
  },
  {
    path: '/superadmin/approvers',
    label: 'Approver Management',
    icon: 'UserCheck',
    roles: ['SUPER_ADMIN'],
  },
  {
    path: '/superadmin/users',
    label: 'User Management',
    icon: 'Users',
    roles: ['SUPER_ADMIN'],
  },
  // Approver Routes
  {
    path: '/approver',
    label: 'Approvals',
    icon: 'CheckSquare',
    roles: ['L1_APPROVER', 'L2_APPROVER', 'L3_APPROVER'],
  },
  // Employee Routes
  {
    path: '/my-team',
    label: 'My Team',
    icon: 'Users',
    roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN', 'IT_EMPLOYEE'],
  },
  {
    path: '/attendance',
    label: 'My Attendance',
    icon: 'Calendar',
    roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN'],
  },
  {
    path: '/leave',
    label: 'Leave & Remote Work',
    icon: 'Clock',
    roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN'],
  },
  {
    path: '/payroll',
    label: 'My Payroll',
    icon: 'DollarSign',
    roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN'],
  },
  {
    path: '/performance',
    label: 'Performance',
    icon: 'TrendingUp',
    roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN'],
  },
  {
    path: '/documents',
    label: 'Documents',
    icon: 'FileText',
    roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN'],
  },

  {
    path: '/helpdesk',
    label: 'Helpdesk',
    icon: 'Headphones',
    roles: ['EMPLOYEE', 'MANAGER'],
  },
  {
    path: '/timesheet-management',
    label: 'Timesheet Management',
    icon: 'Clock',
    roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN', 'IT_EMPLOYEE', 'L1_APPROVER', 'L2_APPROVER', 'L3_APPROVER', 'HR', 'RMG', 'SUPER_ADMIN', 'FINANCE_ADMIN', 'FACILITIES_ADMIN'],
    children: [
      {
        path: '/timesheet-management/uda-configuration',
        label: 'UDA Configuration',
        icon: 'Settings',
        roles: ['RMG', 'SUPER_ADMIN'],
      },
      {
        path: '/timesheet-management/weekly-timesheet',
        label: 'Timesheet Entry',
        roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN', 'IT_EMPLOYEE', 'L1_APPROVER', 'L2_APPROVER', 'L3_APPROVER', 'HR', 'RMG', 'SUPER_ADMIN', 'FINANCE_ADMIN', 'FACILITIES_ADMIN'],
      },
    ],
  },
  // Manager Routes
  {
    path: '/manager/dashboard',
    label: 'Manager Dashboard',
    icon: 'LayoutDashboard',
    roles: ['MANAGER'],
  },
  {
    path: '/manager/leave-approvals',
    label: 'Leave Approvals',
    icon: 'ClipboardCheck',
    roles: ['MANAGER'],
  },
  // IT Admin Routes
  {
    path: '/itadmin/dashboard',
    label: 'IT Admin Dashboard',
    icon: 'Shield',
    roles: ['IT_ADMIN'],
  },
  {
    path: '/itadmin/tickets',
    label: 'Ticket Management',
    icon: 'Ticket',
    roles: ['IT_ADMIN', 'IT_EMPLOYEE'],
  },
  {
    path: '/itadmin/analytics',
    label: 'Analytics',
    icon: 'BarChart',
    roles: ['IT_ADMIN', 'IT_EMPLOYEE'],
  },
  // Finance Admin Routes
  {
    path: '/financeadmin/dashboard',
    label: 'Finance Admin Dashboard',
    icon: 'Wallet',
    roles: ['FINANCE_ADMIN'],
  },
  {
    path: '/financeadmin/tickets',
    label: 'Finance Tickets',
    icon: 'Ticket',
    roles: ['FINANCE_ADMIN', 'EMPLOYEE'],
  },
  {
    path: '/financeadmin/analytics',
    label: 'Analytics',
    icon: 'BarChart',
    roles: ['FINANCE_ADMIN'],
  },
  // Facilities Admin Routes
  {
    path: '/facilitiesadmin/dashboard',
    label: 'Facilities Admin Dashboard',
    icon: 'Building2',
    roles: ['FACILITIES_ADMIN'],
  },
  {
    path: '/facilitiesadmin/tickets',
    label: 'Facilities Tickets',
    icon: 'Ticket',
    roles: ['FACILITIES_ADMIN', 'EMPLOYEE'],
  },
  {
    path: '/facilitiesadmin/analytics',
    label: 'Analytics',
    icon: 'BarChart',
    roles: ['FACILITIES_ADMIN'],
  },
  // Common Routes (All Roles)
  {
    path: '/employees-directory',
    label: 'Employees',
    icon: 'Users',
    roles: ['EMPLOYEE', 'MANAGER', 'IT_ADMIN', 'HR', 'RMG'],
  },
  // HR Routes
  {
    path: '/employees',
    label: 'Employee Management',
    icon: 'Users',
    roles: ['HR'],
  },
  {
    path: '/attendance-management',
    label: 'Attendance Management',
    icon: 'CalendarCheck',
    roles: ['HR'],
  },
  {
    path: '/leave-management',
    label: 'Leave Management',
    icon: 'ClipboardList',
    roles: ['HR'],
  },
  {
    path: '/payroll-management',
    label: 'Payroll Management',
    icon: 'Wallet',
    roles: ['HR'],
  },
  {
    path: '/recruitment',
    label: 'Recruitment',
    icon: 'UserPlus',
    roles: ['HR'],
  },
  {
    path: '/performance-management',
    label: 'Performance Management',
    icon: 'Target',
    roles: ['HR'],
  },
  {
    path: '/ctc-master',
    label: 'CTC Master',
    icon: 'IndianRupee',
    roles: ['HR'],
  },
  {
    path: '/admin-announcements',
    label: 'Announcements Admin',
    icon: 'Megaphone',
    roles: ['HR', 'SUPER_ADMIN'],
  },
  // RMG Routes
  {
    path: '/resource-pool',
    label: 'Resource Pool',
    icon: 'Database',
    roles: ['RMG'],
  },
  {
    path: '/allocations',
    label: 'Allocations',
    icon: 'GitBranch',
    roles: ['RMG'],
  },
  {
    path: '/utilization',
    label: 'Utilization',
    icon: 'Activity',
    roles: ['RMG'],
  },
  {
    path: '/forecasting',
    label: 'Demand Forecasting',
    icon: 'LineChart',
    roles: ['RMG'],
  },
  {
    path: '/rmg/analytics',
    label: 'Analytics Dashboard',
    icon: 'TrendingUp',
    roles: ['RMG'],
  },
  {
    path: '/rmg/customers',
    label: 'Customers',
    icon: 'Building',
    roles: ['RMG'],
  },
  {
    path: '/rmg/projects',
    label: 'Projects',
    icon: 'Briefcase',
    roles: ['RMG'],
  },
  {
    path: '/rmg/customer-pos',
    label: 'Purchase Orders',
    icon: 'FileText',
    roles: ['RMG'],
  },
  {
    path: '/rmg/financial-lines',
    label: 'Financial Lines',
    icon: 'DollarSign',
    roles: ['RMG'],
  },
  {
    path: '/rmg/reports/employee-hours',
    label: 'Employee Hours Report',
    icon: 'BarChart3',
    roles: ['EMPLOYEE', 'MANAGER', 'RMG', 'HR', 'SUPER_ADMIN'],
  },
  // Common Routes
  {
    path: '/reports',
    label: 'Reports',
    icon: 'BarChart3',
    roles: ['HR', 'RMG'],
  },
];

export function hasPermission(userRole: UserRole, path: string): boolean {
  return rolePermissions[userRole]?.includes(path) || false;
}

export function getNavigationForRole(userRole: UserRole): RoutePermission[] {
  return navigationConfig.filter((nav) => nav.roles.includes(userRole));
}
